---
title: "SES_Anat_Analyses Q>=4"
author: "Lindsay Olson"
date: "2/2/2021"
output: 
  html_document:
    toc: TRUE
#output:
 # pdf_document:
  #    extra_dependencies: ["float"]
---

```{r setup, include=FALSE}

library(float)
library(tidyverse)
library(knitr)
library(ggplot2)
library(knitr)
library(MBESS)
library(dplyr)
library(ppcor)
library(corrplot)
library(Hmisc)
library(dplyr)
library(kableExtra)
#library(pander)
library(sjPlot)
library(sjmisc)
library(sjlabelled)
library(stargazer)


options(digits = 4, scipen = 999)


knitr::opts_chunk$set(warning=FALSE, message=FALSE, error = FALSE)

```


### Read in and format LGI dataset
```{r, data-readin, include=FALSE, echo=FALSE, warning=FALSE}

# Read in dataset

#LGI Data 
rm(list=ls()) ## clear the workspace
#dev.off() ## Clear the plots


anat_data = read.csv('/Users/lolson/Documents/001_JDP/001_BDIL/006_Projects/11_ToddlerSES/todanatomicaldata/SES_Anat_v2_q45.csv')

## Recode some Vars
anat_data$dxCoded <- as.factor(anat_data$Dx) # 1 = ASD, 2 = TD
anat_data$dxCoded <-unclass(anat_data$dxCoded)
 
anat_data$sexCoded <- as.factor(anat_data$SEX) # 1 = Female, 2 = Male
anat_data$sexCoded <-unclass(anat_data$sexCoded)



```

### Plot bivariate correlations
```{r corrplots, include=TRUE, echo=FALSE, warning=FALSE,  fig.show='asis', fig.width=7, fig.asp=1, fig.cap='Bivariate Plot'}



SES_Lang_LGI <- rcorr(as.matrix(anat_data[,c("dxCoded", "MEL_cat", "INR", "SES1", "SES2", "zipIncome","lh_transversetemporal_lgi", "rh_transversetemporal_lgi", "lh_superiortemporal_lgi", "rh_superiortemporal_lgi", "lh_middletemporal_lgi", "rh_middletemporal_lgi", "lh_parsopercularis_lgi", "rh_parsopercularis_lgi", "lh_parsorbitalis_lgi", "rh_parsorbitalis_lgi", "lh_parstriangularis_lgi", "rh_parstriangularis_lgi", "TBV")], use="pairwise.complete.obs"))

#mypath <- file.path("/Users/lolson/Documents/001_JDP/001_BDIL/006_Projects/11_ToddlerSES/todanatomicaldata/corrPlots/LGI", "SES_LGI_varsCorr_q45.tiff")
#tiff(file=mypath,width = 10, height = 10, units = 'in', res = 300)
corrplot(SES_Lang_LGI$r, method = "color",  type = "lower", outline = T, addgrid.col = "darkgray", order="original", 
         cl.pos = "b", tl.col = "indianred4", tl.srt = 45,
         p.mat = SES_Lang_LGI$P, sig.level = 0.05, insig = "blank",
         tl.cex = .75, cl.cex = .75, addCoef.col = "white", number.digits = 2, number.cex = 0.5, 
         col = colorRampPalette(c("midnightblue","white","darkred"))(100))
#dev.off()
```

### Plot bivariate correlations, ASD Only
```{r corrplots-ASD, include=TRUE, echo=FALSE, warning=FALSE, fig.show='asis', fig.width=7, fig.asp=1, fig.cap='Bivariate Plot ASD Only'}


anat_data_ASD <- subset(anat_data, anat_data$Dx == "ASD")

options(digits = 2)
SES_corr_ASD <- rcorr(as.matrix(anat_data_ASD[,c("MEL_cat", "INR", "SES1", "SES2", "zipIncome","lh_transversetemporal_lgi", "rh_transversetemporal_lgi", "lh_superiortemporal_lgi", "rh_superiortemporal_lgi", "lh_middletemporal_lgi", "rh_middletemporal_lgi", "lh_parsopercularis_lgi", "rh_parsopercularis_lgi", "lh_parsorbitalis_lgi", "rh_parsorbitalis_lgi", "lh_parstriangularis_lgi", "rh_parstriangularis_lgi", "TBV")], use="pairwise.complete.obs"))


corrplot(SES_corr_ASD$r, method = "color",  type = "lower",outline = T, order="original", 
         cl.pos = "b", tl.col = "indianred4", tl.srt = 45,
         p.mat = SES_Lang_LGI$P, sig.level = 0.05, insig = "blank",
         tl.cex = .75, cl.cex = .75, addCoef.col = "white", number.digits = 2, number.cex = 0.5, 
         col = colorRampPalette(c("midnightblue","white","darkred"))(100))
#dev.off()
```

### Plot bivariate correlations, TD Only
```{r corrplots-TD, include=TRUE, echo=FALSE, warning=FALSE, fig.show='asis', fig.width=7, fig.asp=1, fig.cap='Bivariate Plot, TD Only'}



anat_data_TD <- subset(anat_data, anat_data$Dx == "TD")

options(digits = 2)
SES_corr_TD <- rcorr(as.matrix(anat_data_TD[,c("MEL_cat", "INR", "SES1", "SES2", "zipIncome","lh_transversetemporal_lgi", "rh_transversetemporal_lgi", "lh_superiortemporal_lgi", "rh_superiortemporal_lgi", "lh_middletemporal_lgi", "rh_middletemporal_lgi", "lh_parsopercularis_lgi", "rh_parsopercularis_lgi", "lh_parsorbitalis_lgi", "rh_parsorbitalis_lgi", "lh_parstriangularis_lgi", "rh_parstriangularis_lgi", "TBV")], use="pairwise.complete.obs"))

#mypath <- file.path("/Users/lolson/Documents/001_JDP/001_BDIL/006_Projects/11_ToddlerSES/todanatomicaldata/corrPlots/LGI", #"SES_varsCorr_ASD_q45.tiff")
#tiff(file=mypath,width = 10, height = 10, units = 'in', res = 300)
corrplot(SES_corr_TD$r, method = "color",  type = "lower", outline = T, order="original", 
         cl.pos = "b", tl.col = "indianred4", tl.srt = 45,
         p.mat = SES_Lang_LGI$P, sig.level = 0.05, insig = "blank",
         tl.cex = .75, cl.cex = .75, addCoef.col = "white", number.digits = 2, number.cex = 0.5, 
         col = colorRampPalette(c("midnightblue","white","darkred"))(100))
#dev.off()
```


## Iterate through Income:Needs Ratio regression models and save outputs in tables

```{r, regTables, echo = FALSE, include=TRUE, results= 'asis'}
### Iterate Reg Models 
#library(pander)
#panderOptions('knitr.auto.asis', TRUE)
#summary(anat_data)
## Other options: echo=False, warning=FALSE

set.seed(1)

# number of columns in the Lung and Blood data.frames. 22,000 for you?
n <- 14
outcomes <- anat_data[,c(7:20)]
outcomeVars = names(outcomes)

#coVars <- anat_data[,c(4:6, 36)]

#sesVars <- anat_data[,c(37:39, 41:42)]


## INR Models
# run n regressions
my_lms <- lapply(1:n, function(x) lm(outcomes[,x] ~ anat_data$INR + anat_data$TBV +anat_data$V1.Age)) # change the predictors manually

# if you need more info, get full summary call. now you can get whatever, like:
summaries <- lapply(my_lms, summary)
# ...coefficents with p values:
#sapply(summaries, function(x) x$coefficients[, c(1,4)], simplify = FALSE, USE.NAMES = TRUE)
# ...or r-squared values
#sapply(summaries, function(x) c(r_sq = x$r.squared, adj_r_sq = x$adj.r.squared))


  for (i in seq_along(outcomeVars)) {
   # cat('Linear regression results predicting', outcomeVars[[i]], '\n') 
    cat(tab_model(my_lms[i], pred.labels = c("Intercept", "Income:Needs", "TBV", "Age"),
  dv.labels = paste(outcomeVars[[i]]),
  string.pred = "Coeffcient",
  string.ci = "CI (95%)",
  string.p = "p-Value")$knitr,"\n--------\n")
    
  }


```

### INR Results

Income to needs ratio predicts rh_parsopercularis_lgi and rh_fusiform_lgi, controlling for age and TBV (dx not a sig. predictor)

 
