---
title: "SES_Anat_Analyses"
author: "Lindsay Olson"
date: "11/18/2020"
#output: 
 # slidy_presentation:
  #  font_adjustment: -1
   # footer: Created in R
#output:
 # pdf_document:
  #    extra_dependencies: ["float"]
output: 
  html_document:
    toc: TRUE
---

```{r setup, include=FALSE}

library(float)
library(tidyverse)
library(knitr)
library(ggplot2)
library(knitr)
library(MBESS)
library(dplyr)
library(ppcor)
library(corrplot)
library(Hmisc)
library(dplyr)
library(broom)
library(kableExtra)
options(digits = 4, scipen = 999)


knitr::opts_chunk$set(warning=FALSE, message=FALSE, error = FALSE)

```


### Read in and format LGI dataset
```{r, data-readin, include=FALSE, echo=FALSE, warning=FALSE}

# Read in dataset

#LGI Data 
anat_data = read.csv('/Users/lolson/Documents/001_JDP/001_BDIL/006_Projects/11_ToddlerSES/todanatomicaldata/SES_Anat_v2.csv')

## Recode some Vars
anat_data$dxCoded <- as.factor(anat_data$Dx) # 1 = ASD, 2 = TD
anat_data$dxCoded <-unclass(anat_data$dxCoded)
 
anat_data$sexCoded <- as.factor(anat_data$SEX) # 1 = Female, 2 = Male
anat_data$sexCoded <-unclass(anat_data$sexCoded)

```

### Plot bivariate correlations
```{r corrplots, include=TRUE, echo=FALSE, warning=FALSE,  fig.show='asis', fig.width=7, fig.asp=1, fig.cap='Bivariate Plot'}



SES_Lang_LGI <- rcorr(as.matrix(anat_data[,c("dxCoded", "MEL_cat", "INR", "SES1", "SES2", "zipIncome","lh_transversetemporal_lgi", "rh_transversetemporal_lgi", "lh_superiortemporal_lgi", "rh_superiortemporal_lgi", "lh_middletemporal_lgi", "rh_middletemporal_lgi", "lh_parsopercularis_lgi", "rh_parsopercularis_lgi", "lh_parsorbitalis_lgi", "rh_parsorbitalis_lgi", "lh_parstriangularis_lgi", "rh_parstriangularis_lgi", "TBV")], use="pairwise.complete.obs"))

#mypath <- file.path("/Users/lolson/Documents/001_JDP/001_BDIL/006_Projects/11_ToddlerSES/todanatomicaldata/corrPlots/LGI", "SES_LGI_varsCorr_q45.tiff")
#tiff(file=mypath,width = 10, height = 10, units = 'in', res = 300)
corrplot(SES_Lang_LGI$r, method = "color",  type = "lower", outline = T, addgrid.col = "darkgray", order="original", 
         cl.pos = "b", tl.col = "indianred4", tl.srt = 45,
         p.mat = SES_Lang_LGI$P, sig.level = 0.05, insig = "blank",
         tl.cex = .75, cl.cex = .75, addCoef.col = "white", number.digits = 2, number.cex = 0.5, 
         col = colorRampPalette(c("midnightblue","white","darkred"))(100))
#dev.off()
```

### Plot bivariate correlations, ASD Only
```{r corrplots-ASD, include=TRUE, echo=FALSE, warning=FALSE, fig.show='asis', fig.width=7, fig.asp=1, fig.cap='Bivariate Plot ASD Only'}


anat_data_ASD <- subset(anat_data, anat_data$Dx == "ASD")

options(digits = 2)
SES_corr_ASD <- rcorr(as.matrix(anat_data_ASD[,c("MEL_cat", "INR", "SES1", "SES2", "zipIncome","lh_transversetemporal_lgi", "rh_transversetemporal_lgi", "lh_superiortemporal_lgi", "rh_superiortemporal_lgi", "lh_middletemporal_lgi", "rh_middletemporal_lgi", "lh_parsopercularis_lgi", "rh_parsopercularis_lgi", "lh_parsorbitalis_lgi", "rh_parsorbitalis_lgi", "lh_parstriangularis_lgi", "rh_parstriangularis_lgi", "TBV")], use="pairwise.complete.obs"))


corrplot(SES_corr_ASD$r, method = "color",  type = "lower",outline = T, order="original", 
         cl.pos = "b", tl.col = "indianred4", tl.srt = 45,
         p.mat = SES_Lang_LGI$P, sig.level = 0.05, insig = "blank",
         tl.cex = .75, cl.cex = .75, addCoef.col = "white", number.digits = 2, number.cex = 0.5, 
         col = colorRampPalette(c("midnightblue","white","darkred"))(100))
#dev.off()
```

### Plot bivariate correlations, TD Only
```{r corrplots-TD, include=TRUE, echo=FALSE, warning=FALSE, fig.show='asis', fig.width=7, fig.asp=1, fig.cap='Bivariate Plot, TD Only'}



anat_data_TD <- subset(anat_data, anat_data$Dx == "TD")

options(digits = 2)
SES_corr_TD <- rcorr(as.matrix(anat_data_TD[,c("MEL_cat", "INR", "SES1", "SES2", "zipIncome","lh_transversetemporal_lgi", "rh_transversetemporal_lgi", "lh_superiortemporal_lgi", "rh_superiortemporal_lgi", "lh_middletemporal_lgi", "rh_middletemporal_lgi", "lh_parsopercularis_lgi", "rh_parsopercularis_lgi", "lh_parsorbitalis_lgi", "rh_parsorbitalis_lgi", "lh_parstriangularis_lgi", "rh_parstriangularis_lgi", "TBV")], use="pairwise.complete.obs"))

#mypath <- file.path("/Users/lolson/Documents/001_JDP/001_BDIL/006_Projects/11_ToddlerSES/todanatomicaldata/corrPlots/LGI", #"SES_varsCorr_ASD_q45.tiff")
#tiff(file=mypath,width = 10, height = 10, units = 'in', res = 300)
corrplot(SES_corr_TD$r, method = "color",  type = "lower", outline = T, order="original", 
         cl.pos = "b", tl.col = "indianred4", tl.srt = 45,
         p.mat = SES_Lang_LGI$P, sig.level = 0.05, insig = "blank",
         tl.cex = .75, cl.cex = .75, addCoef.col = "white", number.digits = 2, number.cex = 0.5, 
         col = colorRampPalette(c("midnightblue","white","darkred"))(100))
#dev.off()
```

### Regression Model : INR by Left STG

Model is $Left-STG-LGI = intercept + INR +ZipIncome + TBV + \epsilon$

Here are the coefficients:
```{r, STG reg models, include=TRUE, echo=FALSE, warning=FALSE}

model_lhSupTemp_INR <- lm(lh_superiortemporal_lgi ~  INR  + zipIncome + TBV, data=anat_data, na.action = na.exclude)

mycoefs <- tidy(model_lhSupTemp_INR, conf.int=TRUE)
#mycoefs$p.value = cell_spec(mycoefs$p.value, color = ifelse(mycoefs$p.value < 0.05, "red", "black"))

kbl(mycoefs) %>%
  kable_paper(full_width = F) %>%
  kable_styling(bootstrap_options = c("striped", "hover")) %>%
  column_spec(1, bold = T, border_right = T) %>%
  column_spec(5, border_right = T, border_left = T)
  #column_spec(5, background = "yellow")

```





### Partial regression plot, INR by STG LGI
```{r, STG Scatter,  include=TRUE, echo=FALSE, warning=FALSE}
#Here is a partial regression plot

####### Make Partial Reg Plot ##########
modelLH_STG_residTBV <- lm(lh_superiortemporal_lgi ~  TBV + zipIncome, data=anat_data, na.action = na.exclude)
LH_STG_residTBV_zipIncome <- resid(modelLH_STG_residTBV)

# INR, given Dx, ZipIncome, MEL
modelINR_residTBV <- lm(INR ~  TBV + zipIncome, data=anat_data, na.action = na.exclude)
INR_resid_TBV_zipIncome <- resid(modelINR_residTBV)

## Partial correlation coefficient

#df <- anat_data_ASD
#df1 <- df[!is.na(as.numeric(df$INR))&!is.na(df$TBV)&!is.na(df$lh_superiortemporal_lgi),]
#pcor.test(df1$INR, df1$lh_superiortemporal_lgi, df1$TBV, method = c("pearson"))


#df1 <- df[!is.na(df$SES1)&!is.na(df$TBV)&!is.na(df$lh_superiortemporal_lgi),]
#pcor.test(df1$SES1, df1$lh_superiortemporal_lgi, df1$TBV, method = c("pearson"))

#cor.test(df$SES1, df$lh_superiortemporal_lgi)

#cor.test(df$zipIncome, df$lh_transversetemporal_lgi)
## Partial Reg Plot

#mypath <- file.path("/Users/lolson/Documents/001_JDP/001_BDIL/006_Projects/11_ToddlerSES/todanatomicaldata/scatterPlots/LGI", "lh_STG_LGI_ASDvTD_partialReg_q45.tiff")
#tiff(file=mypath,width = 6, height = 6, units = 'in', res = 300)
ggplot(anat_data, aes(x=INR_resid_TBV_zipIncome, y=LH_STG_residTBV_zipIncome, color=Dx, shape=Dx)) +
  geom_point() +
  geom_smooth(method=lm, aes(fill=Dx)) +
  scale_color_manual(values=c("red","blue")) +
  scale_fill_manual(values=c("red","blue")) +
  ylab('Left STG LGI')+
  xlab('Income:Needs Ratio') +
  labs(title="Income:Needs by Left STG LGI") +
  theme_classic()+
  theme(plot.title = element_text(hjust = 0.5))
#dev.off()

```


